### ISSUE TITLE
CentOS on WSL1 can not resolve DNS

### ISSUE THREAD

**Issue by vbem** [mishamosher/CentOS-WSL#3]
pls delete `/etc/resolv.conf` file, for its automatically generation by WSL like microsoft offical Ubuntu 20.04 does. Refer https://github.com/microsoft/WSL-DistroLauncher/blob/2ed9a9335fc89a688a5150c95eff4fbdbc830f25/DistroLauncher/DistroLauncher.cpp#L32

**Comment by mishamosher** [comment]
WSL does not behave that way anymore (since build 17093/version 1803). If you're using an older version of Windows please update, as anything older is out of support. You can always check the lifecycle of Microsoft products [here](https://docs.microsoft.com/en-us/lifecycle/products/).

Please refer to the [official docs](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf) to configure the `/etc/resolv.conf` file generation.

If you're unable to update, the only alternative that I can suggest is to manually edit the `/etc/resolv.conf` file to fit your needs.
