### ISSUE TITLE
cannot start a program using systemctl

### ISSUE THREAD

**Issue by tangly1991** [mishamosher/CentOS-WSL#7]
cannot start a program using systemctl

**Comment by mishamosher** [comment]
Hi there!

systemd is not supported on WSL: [systemctl doesn't work](https://github.com/microsoft/WSL/issues/1579)

There is a Python script that replicates a good portion of the systemctl functionality, which may be of help: [docker systemctl replacement](https://github.com/gdraheim/docker-systemctl-replacement)

**Comment by zljubisic** [comment]
As systemd is now supported by wsl (https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/) can we have it in centos as well?

**Comment by mishamosher** [comment]
@zljubisic

The required config changes for native `systemd` support are very minimal, and there are many other configs that can be applied: https://learn.microsoft.com/en-us/windows/wsl/wsl-config

There is nothing new to "support", because the required under-the-hood `systemd` changes are baked directly into WSL, and not the individual distros images. For now, you're required to opt-in into this functionality, as described in the official WSL docs.

Additionally, this repo aspires to keep a no-modifications 1:1 copy of the GenericCloud image profile for CentOS, for now.
